[package]
name = "floem_vger_renderer"
version.workspace = true
edition = "2021"
repository = "https://github.com/lapce/floem"
description = "A native Rust UI library with fine-grained reactivity"
license.workspace = true

[dependencies]
wgpu = "0.18.0"
floem-vger-rs = { package = "floem-vger", version = "0.2.7" } # Alias library to avoid overlap with subcrate

resvg = { workspace = true }
swash = { workspace = true }
image = { workspace = true }
raw-window-handle = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
floem-peniko = { workspace = true }
floem_renderer = { workspace = true }
