[package]
name = "floem_tiny_skia_renderer"
version.workspace = true
edition = "2021"
repository = "https://github.com/lapce/floem"
description = "A native Rust UI library with fine-grained reactivity"
license.workspace = true

[dependencies]
softbuffer = "0.3.1"
bytemuck = "1.12"

resvg = { workspace = true }
swash = { workspace = true }
image = { workspace = true }
raw-window-handle = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
floem-peniko = { workspace = true }
floem_renderer = { workspace = true }
